require("__strats-voicepacks-base__.helpers")

local vn = "gordon_freeman"

data:extend{
    setting_volume(vn, 3.0), setting_sound(vn, "acquired"),
    setting_sound(vn, "activated"), setting_sound(vn, "alert"),
    setting_sound(vn, "ammo_depleted"), setting_sound(vn, "ammo_pickup"),
    setting_sound(vn, "armor_gone"), setting_sound(vn, "beep"),
    setting_sound(vn, "bell"), setting_sound(vn, "biohazard_detected"),
    setting_sound(vn, "blip"), setting_sound(vn, "boop"),
    setting_sounds(vn, "breathe", "breathe1,breathe2"),
    setting_sound(vn, "buzz"), setting_sound(vn, "danger"),
    setting_sound(vn, "evacuate_area"), setting_sound(vn, "flatline"),
    setting_sound(vn, "fuzz"), setting_sound(vn, "guncock"),
    setting_sound(vn, "health_critical"),
    setting_sounds(vn, "health_dropping", "health_dropping,health_dropping2"),
    setting_sound(vn, "heartbeat"), setting_sound(vn, "hev_damage"),
    setting_sound(vn, "hev_general_fail"), setting_sound(vn, "hiss"),
    setting_sound(vn, "medcharge"), setting_sound(vn, "medshot"),
    setting_sound(vn, "near_death"),
    setting_sounds(vn, "pain", "pain2,pain4,pain5,pain6,pain7"),
    setting_sound(vn, "radiation_detected"), setting_sound(vn, "safe_day"),
    setting_sound(vn, "smallmedkit"), setting_sound(vn, "suitcharge"),
    setting_sound(vn, "suitchargeok"), setting_sound(vn, "time_is_now"),
    setting_sound(vn, "warning"), setting_sound(vn, "weapon_pickup"),
    setting_event(vn, "on_player_armor_inventory_changed__removed", "armor_gone"),
    setting_event(vn, "on_player_armor_inventory_changed__equipped",
                  "suitchargeok"),
    setting_event(vn, "on_player_ammo_inventory_changed__empty", "ammo_depleted"),
    setting_event(vn, "on_player_ammo_inventory_changed__full", "guncock"),
    setting_event(vn, "on_player_gun_inventory_changed__equipped", "guncock"),
    setting_event(vn, "on_player_damaged__hp_critical", "near_death"),
    setting_event(vn, "on_player_damaged__hp_low", "hev_damage"),
    setting_event(vn, "on_player_damaged__hit", "pain"),
    setting_event(vn, "on_player_died", "flatline"),
    setting_event(vn, "on_player_respawned", "activated"),
    setting_event(vn, "on_player_driving_changed_state__enter", "evacuate_area"),
    setting_event(vn, "on_research_finished", "boop"),
    setting_event(vn, "on_research_started", "bell"),
    setting_event(vn, "on_rocket_launch_ordered__riding", "safe_day"),
    setting_event(vn, "on_player_joined_game", "safe_day")
}
